version: "3.7"

volumes:
  mongo:
    name: /data/db/mongodb
    external: true

services:
  mongo:
    image: mongo:4.4.16
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    deploy:
      resources:
        limits:
          cpus: "0.80"
          memory: "512M"
        reservations:
          cpus: "0.40"
          memory: "256M"
